"""
Multi-channel notification delivery — dashboard push, email digest, and logging.
"""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import json
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
from typing import Optional

from alerts.alert_models import Alert
from config.settings import SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASSWORD, ALERT_EMAIL_RECIPIENTS


class DashboardNotifier:
    """Push notifications to the Streamlit dashboard via session state."""

    def __init__(self):
        self.pending_notifications = []

    def push(self, alert: Alert) -> bool:
        """Add notification for dashboard display."""
        self.pending_notifications.append({
            "id": alert.alert_id,
            "type": alert.alert_type,
            "message": alert.message,
            "severity": alert.severity,
            "store_id": alert.store_id,
            "timestamp": alert.created_at or datetime.now().isoformat(),
            "action": alert.suggested_action,
            "corrective_action": alert.corrective_action,  # CHANGE 5
        })
        return True

    def get_pending(self, clear: bool = True) -> list:
        """Get and optionally clear pending notifications."""
        notifications = list(self.pending_notifications)
        if clear:
            self.pending_notifications.clear()
        return notifications

    @property
    def count(self) -> int:
        return len(self.pending_notifications)


class EmailNotifier:
    """Email digest notifications via SMTP."""

    def __init__(self):
        self.enabled = bool(SMTP_USER and SMTP_PASSWORD)

    def send_digest(self, alerts: list, subject: str = "ShelfIQ Alert Digest") -> bool:
        """Send alert digest email."""
        if not self.enabled:
            self._log_email(alerts, subject)
            return False

        try:
            html = self._build_html(alerts)
            msg = MIMEMultipart("alternative")
            msg["Subject"] = subject
            msg["From"] = SMTP_USER
            msg["To"] = ", ".join(ALERT_EMAIL_RECIPIENTS)
            msg.attach(MIMEText(html, "html"))

            with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
                server.starttls()
                server.login(SMTP_USER, SMTP_PASSWORD)
                server.send_message(msg)

            return True
        except Exception as e:
            print(f"  ⚠ Email send failed: {e}")
            self._log_email(alerts, subject)
            return False

    def _build_html(self, alerts: list) -> str:
        """Build HTML email content."""
        severity_colors = {5: "#dc3545", 4: "#e83e8c", 3: "#fd7e14", 2: "#ffc107", 1: "#17a2b8"}
        rows = ""
        for a in alerts:
            sev = a.severity if isinstance(a, Alert) else a.get("severity", 1)
            color = severity_colors.get(sev, "#6c757d")
            msg = a.message if isinstance(a, Alert) else a.get("message", "")
            atype = a.alert_type if isinstance(a, Alert) else a.get("alert_type", "")
            store = a.store_id if isinstance(a, Alert) else a.get("store_id", "")
            rows += f"""
            <tr>
                <td style="border-left: 4px solid {color}; padding: 8px;">{atype}</td>
                <td style="padding: 8px;">{store}</td>
                <td style="padding: 8px;">{msg}</td>
            </tr>"""

        return f"""
        <html>
        <body style="font-family: Arial, sans-serif; background: #f8f9fa; padding: 20px;">
            <div style="max-width: 600px; margin: auto; background: white; border-radius: 8px; padding: 20px;">
                <h2 style="color: #1a1a2e;">🛒 ShelfIQ — Alert Digest</h2>
                <p>{len(alerts)} alert(s) require attention:</p>
                <table style="width: 100%; border-collapse: collapse;">
                    <tr style="background: #f1f1f1;">
                        <th style="padding: 8px; text-align: left;">Type</th>
                        <th style="padding: 8px; text-align: left;">Store</th>
                        <th style="padding: 8px; text-align: left;">Message</th>
                    </tr>
                    {rows}
                </table>
                <p style="margin-top: 20px; font-size: 12px; color: #888;">
                    Generated by ShelfIQ at {datetime.now().strftime("%Y-%m-%d %H:%M")}
                </p>
            </div>
        </body>
        </html>"""

    def _log_email(self, alerts: list, subject: str):
        """Log email content when SMTP is not configured."""
        print(f"  📧 [EMAIL LOG] {subject} — {len(alerts)} alerts")
        for a in alerts[:3]:
            msg = a.message if isinstance(a, Alert) else a.get("message", "")
            print(f"     → {msg}")
        if len(alerts) > 3:
            print(f"     ... and {len(alerts) - 3} more")


class MobileNotifier:
    """Simulated mobile push notification (logs for demo)."""

    def push(self, alert: Alert) -> bool:
        """Simulate sending a mobile push notification."""
        icon = {"STOCKOUT": "🔴", "LOW_STOCK": "🟡", "PLANOGRAM_VIOLATION": "🟠", "PRICE_MISMATCH": "🔵"}
        emoji = icon.get(alert.alert_type, "⚪")
        print(f"  📱 [MOBILE PUSH] {emoji} {alert.message} ({alert.store_id})")
        return True


class NotificationRouter:
    """Routes alerts to appropriate notification channels."""

    def __init__(self):
        self.dashboard = DashboardNotifier()
        self.email = EmailNotifier()
        self.mobile = MobileNotifier()

    def notify(self, alert: Alert, channels: list = None):
        """Send alert through specified channels."""
        channels = channels or ["dashboard", "mobile"]

        for channel in channels:
            if channel == "dashboard":
                self.dashboard.push(alert)
            elif channel == "email":
                self.email.send_digest([alert])
            elif channel == "mobile":
                self.mobile.push(alert)

    def notify_batch(self, alerts: list, channels: list = None):
        """Send batch of alerts."""
        channels = channels or ["dashboard"]
        for alert in alerts:
            self.notify(alert, channels)

        # Send consolidated email for batch
        if "email" in (channels or []):
            self.email.send_digest(alerts)

    def get_dashboard_notifications(self) -> list:
        return self.dashboard.get_pending()


# Singleton
notifier = NotificationRouter()
