[theme]
primaryColor = "#6ee6ee"
backgroundColor = "#0b1323"
secondaryBackgroundColor = "#141b2c"
textColor = "#dbe2f9"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
